services:
  ultracar-api:
    image: ultracar-api
    build: .
    ports:
      - "8080:8080"
    links:
      - pg
    restart: always
    environment:
      - DATABASE_URL=jdbc:postgresql://pg:5432/ultracar_db
      - SPRING_DATASOURCE_USERNAME=ultracar
      - SPRING_DATASOURCE_PASSWORD=my-secret
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: bitnami/postgresql:13.16.0
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=ultracar
      - POSTGRES_PASSWORD=my-secret
      - POSTGRES_DB=ultracar_db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ultracar" ]
      interval: 10s
      timeout: 5s
      retries: 5

